(function initSiteCopyConfig() {
  const siteCopy = Object.freeze({
    meta: {
      documentTitle: "Dota2 宁德联赛",
      // betaNoticePrefix: "测试版：积分榜 + 比赛记录, 项目启动于北京时间 2026/4/1 19:30:59, 最后更新于 ",
    },
    brand: {
      kicker: "DOTA 2 COMMUNITY LEAGUE",
      mainTitle: "宁德联赛",
      loadingStatus: "正在载入赛季和比赛数据...",
    },
    header: {
      scorerMode: "记录员模式",
      adminMode: "管理员模式",
      signIn: "账号登录",
      signOut: "退出登录",
      seasonToggleLoading: "赛季选手",
      seasonRewardTotalDefault: "本赛季赞助总额：--",
    },
    scorerPanel: {
      title: "记录员面板",
      exit: "退出登录",
      collapse: "收起",
      toolsTitle: "工具",
      scoreToolButton: "积分操作",
      pointRuleButton: "设置积分规则",
      powerManageButton: "战力管理",
      playerManageButton: "选手管理",
      manualScoreTitle: "积分操作",
      manualScoreAmountPlaceholder: "分值，输入正数",
      manualScoreApplyLoss: "确认扣分",
      manualScoreApplyGain: "确认加分",
      itemManageButton: "添加道具",
      itemManageSectionTitle: "道具信息",
      itemHistoryButtonAriaLabel: "查看选手道具变动日志",
      itemHistoryTitle: "选手道具变动日志",
      itemHistoryEmpty: "当前还没有道具变动记录",
      itemRevokeAction: "扣除",
      finishToday: "今日比赛全部完结",
      recalculate: "重算积分",
      clearQueue: "清空报名队列",
      matchRuleTitle: "胜负积分规则",
      matchRuleDescription: "胜方基础加分;负方基础扣分;战力有效分差;战力分差导致的积分变动",
      seasonInitialScorePlaceholder: "赛季初始分",
      seasonInitialScoreSave: "设置赛季初始分",
      seasonWinPointsPlaceholder: "胜方基础加分",
      seasonLossPointsPlaceholder: "负方基础扣分",
      powerGapStepPlaceholder: "战力差",
      powerGapDeltaPlaceholder: "每档修正",
      seasonMatchPointSave: "保存积分规则",
      manualNotePlaceholder: "备注，可选",
      deathFinger: "死亡一指 -1",
      healingHand: "治疗之手 +1",
      rankLabelSave: "保存战力值",
      rosterTitle: "选手信息管理",
      quickAddPlaceholder: "输入新选手名字",
      quickAddAction: "添加选手",
      renamePlayerDefault: "请选择现有选手",
      renamePlayerPlaceholder: "输入新的选手名字",
      renamePlayerAction: "确认更名",
      hidePlayerAction: "删除选手",
      logsButton: "操作日志",
      logsTitle: "操作日志",
      logsEmpty: "当前还没有操作记录",
      dailyBonusHeroesAction: "每日奖励英雄",
    },
    adminPanel: {
      title: "管理员面板",
      summaryLoading: "加载中...",
      exit: "退出登录",
      collapse: "收起",
      toolsTitle: "工具",
      scoreToolButton: "积分操作",
      pointRuleButton: "设置积分规则",
      powerManageButton: "战力管理",
      playerManageButton: "选手管理",
      manualScoreTitle: "积分操作",
      manualScoreAmountPlaceholder: "分值，输入正数",
      manualScoreApplyLoss: "确认扣分",
      manualScoreApplyGain: "确认加分",
      itemManageButton: "添加道具",
      itemManageSectionTitle: "道具信息",
      itemHistoryButtonAriaLabel: "查看选手道具变动日志",
      itemHistoryTitle: "选手道具变动日志",
      itemHistoryEmpty: "当前还没有道具变动记录",
      itemRevokeAction: "扣除",
      recalculate: "重算积分",
      finishToday: "今日比赛全部完结",
      clearQueue: "清空报名队列",
      clearTodayPlayers: "清空当日选手",
      resetSeason: "重置当前赛季",
      exportSeasonAction: "导出赛季到 GitHub",
      prizeDistributionAction: "分配赛季奖金",
      participationRulesAction: "修改场次分",
      backgroundPickerAction: "更换背景",
      backgroundPickerTitle: "网站背景",
      backgroundPickerClose: "关闭",
      backgroundPickerApply: "应用背景",
      backgroundPickerFinalDay: "决赛日背景",
      backgroundPickerBrightness: "蒙板明度（明暗）",
      backgroundUploadLabel: "上传背景",
      backgroundPickerPlayerSettings: "专属背景设置",
      backgroundPickerPlayerLabel: "选手",
      backgroundPickerPlayerSave: "保存专属背景",
      backgroundPickerPlayerClear: "清除该选手",
      backgroundPickerPlayerEmpty: "当前还没有专属背景。",
      backgroundPickerPlayerRemove: "移除",
      participationRulesTitle: "场次分规则",
      participationRulesClose: "关闭",
      participationRulesPlaceholder: "-10,0\n11-17,15\n18-25,25\n50+,25\n71+,~5",
      participationRulesHint: "每行一条“场次范围,分值”；-10,0 表示 0-10 场总分为 0；18-25,25 表示区间总分为 25；50+,25 表示 50 场及以上总分固定 25；71+,~5 表示从 71 场起每场递增 5 分。",
      participationRulesSave: "保存场次分",
      clearRememberedDevices: "清空所有记分员自动登录",
      matchRuleTitle: "胜负积分规则",
      matchRuleDescription: "胜方基础加分;负方基础扣分;战力有效分差;战力分差导致的积分变动",
      seasonInitialScorePlaceholder: "赛季初始分",
      seasonInitialScoreSave: "设置赛季初始分",
      seasonWinPointsPlaceholder: "胜方基础加分",
      seasonLossPointsPlaceholder: "负方基础扣分",
      powerGapStepPlaceholder: "战力差",
      powerGapDeltaPlaceholder: "每档修正",
      seasonMatchPointSave: "保存积分规则",
      manualNotePlaceholder: "备注，可选",
      deathFinger: "死亡一指 -1",
      healingHand: "治疗之手 +1",
      rankLabelSave: "保存战力值",
      rosterTitle: "选手信息管理",
      quickAddPlaceholder: "输入新选手名字",
      quickAddAction: "添加选手",
      renamePlayerDefault: "请选择现有选手",
      renamePlayerPlaceholder: "输入新的选手名字",
      renamePlayerAction: "确认更名",
      hidePlayerAction: "删除选手",
      hiddenPlayersTitle: "已删除选手",
      hiddenPlayersHint: "恢复会重新显示选手；永久删除仅用于没有历史记录的误建选手。",
      restorePlayerAction: "恢复选手",
      hardDeletePlayerAction: "永久删除",
      scorersTitle: "记分员",
      scorersCountDefault: "0 人",
      addScorerDefault: "请选择总表选手",
      addScorerAction: "新增记分员",
      logsButton: "操作日志",
      logsTitle: "操作日志",
      logsEmpty: "当前还没有操作记录",
      dailyBonusHeroesAction: "每日奖励英雄",
    },
    rewards: {
      title: "赛季赞助",
      // description: "点选选手后登记赞助。",
      collapse: "收起",
      amountPlaceholder: "赞助额",
      addAction: "添加赞助",
      signupFeePaidToggle: "确认",
      signupFeePaidBadge: "已确认",
      minimumHint: "点选一位选手",
      empty: "暂无赛季赞助数据",
    },
    seasonPlayers: {
      title: "赛季选手",
      countDefault: "0 人",
      rolloverAction: "赛季完结",
      resetSeason: "重置当前赛季",
      empty: "当前赛季暂无选手",
    },
    todayPlayers: {
      title: "当日选手名单",
      countDefault: "0 人",
      empty: "今日尚未确认到场选手",
    },
    matchDay: {
      title: "当日比赛",
      statusDefault: "未发起",
      startTimePlaceholder: "请输入开始时间，留空默认19:30",
      startAction: "发起当日比赛",
    },
    leaderboard: {
      title: "积分榜",
      powerViewAriaLabel: "查看战力",
      participationViewAriaLabel: "查看场次分",
      championsAriaLabel: "查看历届冠军",
      championsTitle: "历届冠军",
      championsStatusIdle: "",
      championsStatusLoading: "冠军读取中...",
      championsStatusReady: "",
      championsStatusPartial: "部分已完结赛季冠军读取失败。",
      championsClose: "关闭",
      championsEmpty: "当前暂无已完结赛季冠军。",
      copyAriaLabel: "复制积分榜文本",
      rankColumn: "排名",
      playerColumn: "玩家",
      scoreColumn: "积分",
      gamesColumn: "场次",
      winRateColumn: "胜率",
    },
    signup: {
      title: "报名",
      signupAll: "全部报名",
      empty: "加载中...",
    },
    queue: {
      title: "当前报名队列",
      confirmAllReady: "全部到齐",
      clearQueue: "测试清空报名队列",
      empty: "当前无人报名",
    },
    recentMatches: {
      title: "最近比赛记录",
      addTodayMatch: "添加当日比赛",
      backfillMatch: "比赛补录",
      matchFormTitle: "当日比赛登记",
      liveSaveBadge: "即时保存",
      radiantTeam: "天辉方",
      direTeam: "夜魇方",
      winnerToggleHint: "",
      matchWinnerPending: "胜负未定，先保存不计分",
      matchWinnerRadiant: "天辉方获胜",
      matchWinnerDire: "夜魇方获胜",
      matchNotePlaceholder: "备注，可选",
      saveMatch: "保存比赛记录",
      collapse: "收起",
      backfillTitle: "历史比赛补录",
      backfillDescription: "用于补录漏记的历史比赛，可选择赛季和当日之前的日期。",
      archiveBadge: "历史归档",
      selectSeasonDefault: "请选择赛季",
      backfillDateLabel: "补录日期",
      backfillNotePlaceholder: "补录备注，可选",
      saveBackfill: "保存补录比赛",
      empty: "暂无比赛记录",
    },
    dailyBonusHeroes: {
      title: "每日奖励英雄",
      managementTitle: "每日奖励英雄",
      managementDescription: "开启后持续生效。每天北京时间 02:00 与网站统一刷新时间同步更换，也可手动更换当前业务日的种子。",
      close: "关闭",
      enabledLabel: "开启每日奖励英雄",
      enabledStatus: "已开启",
      disabledStatus: "已关闭",
      countLabel: "每日英雄个数",
      pointsLabel: "对应奖励分数",
      pointsHint: "按抽取顺序设置，不绑定具体英雄",
      positionLabel: "第 {index} 个英雄",
      seedLabel: "今日随机数种子",
      seedPlaceholder: "输入 0 至 4294967295",
      applySeed: "使用种子更换",
      randomize: "自动生成种子更换",
      save: "保存设置",
      previewTitle: "今日预览",
    },
    accessModal: {
      title: "账号登录",
      close: "关闭",
      playerPickerLabel: "选手",
      usernameLabel: "用户名或邮箱",
      usernamePlaceholder: "请输入用户名",
      passwordLabel: "密码",
      passwordPlaceholder: "请输入密码",
      submit: "登录",
    },
    heroPicker: {
      title: "选择英雄",
      subtitle: "可直接留空，后续也能补填。",
      close: "关闭",
      searchPlaceholder: "输入英文、中文或拼音首字母搜索英雄",
      emptyOption: "不选择英雄",
      save: "保存英雄",
      clear: "清空英雄",
    },
    scoreDetail: {
      title: "积分变动明细",
      subtitle: "起始 10 分",
      close: "关闭",
    },
    relationStats: {
      title: "选手胜率关系统计",
      subtitle: "查看队友与对手层面的胜率表现。",
      playerLabel: "选手",
      seasonLabel: "赛季",
      monthLabel: "月份",
      minGamesLabel: "最小样本",
      teammateChartTitle: "队友协同网络",
      opponentChartTitle: "对手对局网络",
      tableTitle: "关系明细",
      tableSubtitle: "可按列排序，低样本会单独标记。",
      close: "关闭",
    },
    runtime: {
      accessRoleLabels: {
        admin: "管理员",
        scorekeeper: "记分员",
        scorer: "记分员",
      },
      common: {
        viewer: "游客",
        signIn: "账号登录",
        scorerModeOpen: "收起记录",
        scorerModeClosed: "记录员模式",
        adminModeOpen: "收起管理",
        adminModeClosed: "管理员模式",
      },
      accessModal: {
        title: "账号登录",
        playerPickerEmpty: "暂无选手",
        missingUsername: "请输入用户名",
        missingPassword: "请输入密码",
        loggingIn: "登录中...",
        loginSuccessSyncing: "登录成功",
        loginFailed: "登录失败",
      },
      rolePanels: {
        // roleControlLoggedIn: "账号角色控制",
        roleControlLoggedOut: "未登录",
        roleHintLoggedIn: "",
        roleHintLoggedOut: "登录后会根据账号角色显示记录员或管理员入口。",
        adminSummaryLoggedIn: "当前登录身份：{role};   最后更新于{lastUpdated};   GitHub：{githubStorage};   {supabaseUsage}",
        adminSummaryLoggedOut: "请先登录管理员账号。",
      },
      scorerPanel: {
      },
      players: {
        unnamedPlayer: "未命名选手",
        scorerOptionDefault: "若为记分员，请选择对应选手",
        adminAddDefault: "请选择总表选手",
        renameDefault: "请选择现有选手",
        noAvailablePlayers: "当前还没有可选选手。",
        quickAddMissingName: "请输入选手名字。",
        quickAddPending: "正在添加选手...",
        quickAddFailed: "添加选手失败：{message}",
        quickAddSuccess: "已添加选手：{name}",
        renameMissingTarget: "请先选择要更名的选手。",
        renameMissingName: "请输入新的选手名字。",
        renameSameName: "新名字和当前名字相同。",
        renamePending: "正在更新选手名字...",
        renameFailed: "更名失败：{message}",
        renameSuccess: "已将 {from} 更名为 {to}。",
        renameToast: "已更新选手名字：{name}",
        noHiddenPlayers: "当前没有被删除的选手。",
        deleteMissingTarget: "请先选择要删除的选手。",
        deleteConfirm: "确认删除选手「{name}」吗？该操作不会从数据库真实删除记录，可由管理员恢复。",
        deletePending: "正在删除选手...",
        deleteFailed: "删除选手失败：{message}",
        deleteSuccess: "已删除选手：{name}",
        restoreMissingTarget: "请先选择要恢复的已删除选手。",
        restorePending: "正在恢复选手...",
        restoreFailed: "恢复选手失败：{message}",
        restoreSuccess: "已恢复选手：{name}",
        hardDeleteMissingTarget: "请先选择要永久删除的已删除选手。",
        hardDeleteConfirm: "确认从数据库永久删除「{name}」吗？此操作不可恢复。",
        hardDeleteNamePrompt: "请再次输入选手名字「{name}」确认永久删除。",
        hardDeleteNameMismatch: "确认文字不匹配，已取消永久删除。",
        hardDeletePending: "正在永久删除选手...",
        hardDeleteFailed: "永久删除选手失败：{message}",
        hardDeleteSuccess: "已从数据库永久删除选手：{name}",
      },
    },
  });

  window.__DOTA2SYS_SITE_COPY__ = siteCopy;

  if (typeof document !== "undefined") {
    document.title = siteCopy.meta?.documentTitle || document.title;
  }
}());
